### ISSUE TITLE
send help

### ISSUE THREAD

**Issue by Chiroyce1** [Chiroyce1/image#4]
css aaaaaaa

<img width="328" alt="image" src="https://github.com/Chiroyce1/image/assets/97374054/09c9513a-9f28-4990-83f7-cc83b707989c">

cc @MystPi @mybearworld cuz i cant be bothered sorry lol

**Comment by Chiroyce1** [comment]
i spent 15 minutes making this site responsive and look decent and now i realise that the buttons are off by like 0.5px 😭

**Comment by mybearworld** [comment]
`display:flex` on the `.inp` makes it work :P

**Comment by Chiroyce1** [comment]
uhhh 
<img width="1064" alt="image" src="https://github.com/Chiroyce1/image/assets/97374054/feda8cf7-d2d1-4075-b0c3-452f9cf796bd">

**Comment by mybearworld** [comment]
You need to remove the margin from the "Load image" button
